spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: serdar
    password: serdar
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
    port: 10001
    
diski:
  resourceId: serdarDiski
  clientId: 8ddsa565dsa87787IuJ6NVIBDKCh4cBdslds65ds
  clientSecret: h4cIhSjZjs
  endPointUrl: http://localhost:10000/oauth/check_token/